o bumped to maven-reporting-api:2.0.8-SNAPSHOT and maven-reporting-impl:2.1-SNAPSHOT o bumped to maven:2.0.7 o excluded plexus:plexus-utils o bumped plexus-utils:1.4.5 o added maven prerequisite:2.0.6 o added doxia-core:1.0-beta-1-SNAPSHOT and doxia-site-renderer:1.0-beta-1-SNAPSHOT. Why beta and not alpha-9? I didn't understand why plexus needs them. Without beta, I got the following when running tests: java.lang.NoSuchMethodError: org.codehaus.plexus.PlexusContainer.setConfigurationResource(Ljava/io/Reader;)V o updated test case
git-svn-id: https://svn.apache.org/repos/asf/maven/plugins/trunk@580581 13f79535-47bb-0310-9956-ffa450edef68